[project]
name = "agnoplayground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.1.4",
    "openai>=1.63.2",
    "sqlalchemy>=2.0.38",
    "tavily-python>=0.5.1",
]
