apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  type: LoadBalancer
  loadBalancerIP: 104.198.247.48  # Replace with your reserved static IP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
